### ISSUE TITLE
[PE-D][Tester D] Add Command does not behave as expected

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T13-2/tp#219] opened 2023-03-31 18:27 UTC
I tried the following command:
- `add n/Recipe 3 i/-n Ingredient 1 -a 100 g` 

The following exception occurred in my terminal:

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/721331cb-bc7c-4edd-aad2-0c9bf90e6551.png)

Then, I tried the following command:
- `add n/Recipe 3 i/-nIngredient 1 -a 100 g` 

The app gives me the following error message:

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/cddfc8bc-dc65-4cb2-b621-21749b76a5ef.png)

I am not too sure what went wrong because I followed the format as stated in the UG:

![image.png](https://raw.githubusercontent.com/eugenetangkj/ped/main/files/5a30e1b7-d407-4d49-9663-9f0f6d1f82c0.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: eugenetangkj/ped#5

**Comment by filbertphang** [comment] 2023-04-02 17:58
errors fixed in #245 

wrong UG command is duplicate of #238

**Closed** 2023-04-10 09:59 UTC
Labels: UG Issue, Regex Validation
