### ISSUE TITLE
[PE-D][Tester E] Add form's ingredient placeholder text shows wrong format

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T13-2/tp#223] opened 2023-03-31 19:00 UTC
The place holder text in add form's ingredient textbox shows wrong input format.

![image.png](https://raw.githubusercontent.com/shazxrin/ped/main/files/da9167a3-3b89-4f6f-81ff-6bf0e428ea7f.png)

![image.png](https://raw.githubusercontent.com/shazxrin/ped/main/files/c20f4fc2-d003-4c3f-b81f-9275e087d08c.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: shazxrin/ped#4

**Comment by filbertphang** [comment] 2023-04-02 17:56
duplicate of #232

**Closed** 2023-04-08 12:55 UTC
Labels: Code Issue, GUI, Fixed
